### ISSUE TITLE
Library breaks with rocket 0.5.0-rc.2 

### ISSUE THREAD

**Issue by DerPizzaBoi** [tvallotton/rocket_auth#37]
After updating rocket to 0.5.0-rc.2 i am getting this error for every function using either the User, Users or Auth Requestguards

```error[E0282]: type annotations needed
  --> src/routes/index.rs:30:5
   |
30 | pub async fn some_method(user: User) -> SomeReturnType {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^------
   |     |                                                          |
   |     |                                                          consider giving ´___responder´ a type
   |     cannot infer type
```

I am not 100% sure if this is an error in the library, in rocket or in my own code

(This issue is more to report this than to require any fix of this problem)

**Comment by DerPizzaBoi** [comment]
i wrongly identified this. has nothing to do with the library
